# Generated by Django 5.0 on 2024-03-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NB', models.IntegerField()),
                ('Periode_data', models.IntegerField()),
                ('Cout_Commande', models.IntegerField()),
                ('taux_passation', models.IntegerField()),
                ('prix_achat', models.IntegerField()),
            ],
        ),
    ]
